language: node_js
node_js: "0.12"
script: npm run travisci
after_script:
  - codeclimate-test-reporter < coverage/lcov.info
addons:
  code_climate:
    repo_token:
      secure: "EXTHpFvG3SbssLTLkwwZTwAtO5AKsF4E8akUZT7umKALosdN3NakmJSbxtIcMt8g8sqp22sSK2eyhNp8BxbeI8jkh9R69qtRzmkpG9O3HToWuREmMzImIjo8CizkehermIj7n1ATW/pnXpXNz2+8AUSO3lPO7pZFBjnL7sxf5L/c7jigKezLjzG0k0QrLQuyeJ56PEGE/1nBTjkY2ZiA+5VWty6H6BOHSQDrjnjUCoRfWDelqSfnLXvh/AYyyqB67Q2tpb7jdTjoEaNW+vI+rgT944VItiNFDsehbDttZyjJRy5qMf12TyBWii1DS9O3bGrxs1tWp1cIzITTGdnWpZtz+6eexJKa+8i6vRigI4u3uZNS9Mljqz2sUthds+n7g5nAODtjx4HcmT8vlh/q0EyokZMjzXetA/iL8Puh7S3tbd8o823cptAIF/35/x61ZJD9gecaDfggF2yU82oNI7gR/sfwhVNPSQwutbQgssxrohBLvWt1qD5hapo2eS9+D/i7wHcSQlgPvYZCPRlDY9EJkZBMg7ux8LXIZ2xOZZP6czSlfefNgfev+M/iVvuyCfFvetKTVutCzXZ5CIJJrsfU7q11mBAC4itMyvzo0TlVeNJTU1llO7VI1w/K5z8VaBElu9r6003rvMF31pqVIOFnQUSnGK2l/AXNUH4ZVyM="
